name: Python application

on:
  push:
    breanchs:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Test with Actions
      run: |
        ls -lh
        bash build2pyz.sh
        ls -lh


  upload:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: release MCLaunhcer.pyz from github.com
        uses: actions/upload-artifact@v2
        with:
          name: MCLauncher.pyz
          path: MCLauncher.pyz

