name: Python application
on:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 跑起来～
      run: |
        ls -lh
        echo "==================="
        bash build2pyz.sh
        echo "==================="
        ls -lh

    # - name: release MCLaunhcer.pyz from github.com
    - name: 保存 MCLaunhcer.pyz
      uses: actions/upload-artifact@v4
      with:
        name: MCLauncher.pyz
        path: MCLauncher.pyz


#  upload:
#    runs-on: ubuntu-latest
#    needs:
#      - build
