name: Python application
on:
  push:
    branches:
      # - master
      - ci

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: 跑起来～
      run: |
        echo "安装uv"
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv python install 3.12
        uv venv build-uv-venv
        source build-uv-venv/bin/activate
        echo "安装uv+启用虚拟环境"
        ls -lh
        echo "==================="
        uv pip install -r requireument.txt
        pyinstaller main.spec
        echo "==================="
        ls -lh

    - name: 保存 MCLaunhcer-${{ runner.os }}
      uses: actions/upload-artifact@v7
      with:
        name: MCLauncher-${{ runner.os }}
        path: dist/MCLauncher

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: 跑起来～
      run: |
        dir
        echo "==================="
        pip install -U --break-system-package -r requireument.txt
        pyinstaller main.spec
        echo "==================="
        dir

    - name: 保存 MCLaunhcer-${{ runner.os }}
      uses: actions/upload-artifact@v7
      with:
        name: MCLauncher-${{ runner.os }}
        path: dist/MCLauncher.exe
