name: Python application
on:
  push:
    branches:
      - master
      - devel

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 跑起来～
      run: |
        ls -lh
        echo "==================="
        pip install -U --break-system-package -r requireument.txt
        pyinstaller main.spec
        echo "==================="
        ls -lh

    - name: 保存 MCLaunhcer-${{ runner.os }}
      uses: actions/upload-artifact@v4
      with:
        name: MCLauncher-${{ runner.os }}
        path: dist/MCLauncher

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 跑起来～
      run: |
        dir
        echo "==================="
        pip install -U --break-system-package -r requireument.txt
        pyinstaller main.spec
        echo "==================="
        dir

    - name: 保存 MCLaunhcer-${{ runner.os }}
      uses: actions/upload-artifact@v4
      with:
        name: MCLauncher-${{ runner.os }}
        path: dist\\MCLauncher.exe

#  upload:
#    runs-on: ubuntu-latest
#    needs:
#      - build
