name: Python application

on:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Test with Actions
      run: |
        ls -lh
        echo "==================="
        bash build2pyz.sh
        echo "==================="
        ls -lh

    - name: release MCLaunhcer.pyz from github.com
      uses: actions/upload-artifact@v2
      with:
        name: MCLauncher.pyz
        path: MCLauncher.pyz


#  upload:
#    runs-on: ubuntu-latest
#    needs:
#      - build
